<h2 align="center">Codebasics DL Course: Tensors in PyTorch 2</h2>

In [2]:
import torch

### Tensor Attributes

In [15]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [17]:
units.shape

torch.Size([3, 2])

In [18]:
units.dtype

torch.int64

In [12]:
units.device

device(type='cpu')

### Tensor Reshaping

In [19]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [20]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [21]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

### Index Operator

In [22]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [23]:
units[2,0]

tensor(300)

In [24]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

### Tensor Creation with Specific Values

In [25]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [27]:
torch.rand((3,5))

tensor([[0.1443, 0.2439, 0.8509, 0.3203, 0.6583],
        [0.2582, 0.3991, 0.6188, 0.8829, 0.6616],
        [0.8776, 0.8054, 0.7032, 0.8534, 0.4898]])